name: google_maps_flutter_example
description: Demonstrates how to use the google_maps_flutter plugin.
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  
  google_maps_flutter_platform_interface:
    git:
      url: https://github.com/tonetaggit/ttflutterpackages.git
      path: packages/google_maps_flutter_platform_interface-2.14.0
      ref: main
  

dev_dependencies:
  build_runner: ^2.1.10
  espresso: ^0.4.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  stream_transform: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
